import Head from 'next/head'
import styles from '@/styles/Home.module.css'

import io, { Socket } from 'socket.io-client'
import { useEffect } from 'react'
import { DefaultEventsMap } from '@socket.io/component-emitter'

const hostname = 'localhost'
const wsPort = '8000'

const endpoint = `ws://${hostname}:${wsPort}`

class _SocketClient {
	private socket?: Socket<DefaultEventsMap, DefaultEventsMap>

	initialize() {
		if (this.isInitialized) return

		this.socket = io(endpoint)

		this.socket.on('connect', () => {
			console.log('connected', this.socket?.id)
		})

		this.socket.on('hello', (ev) => {
			console.log('on hello', { ev })
		})

		this.socket.on('from_server', (ev) => {
			console.log('from_server', { ev })
		})

		this.socket.on('disconnect', () => {
			console.log('disconnect', this.socket?.id)
		})
	}

	sendMessageFromClient() {
		if (!this.socket) return

		this.socket.emit('from_client', 'penis')
	}

	get isInitialized() {
		return !!this.socket
	}
}

const SocketClient = new _SocketClient()

export default function Home() {
	useEffect(() => {
		SocketClient.initialize()
	}, [])

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<h1>Hello World!</h1>
				<button onClick={() => SocketClient.sendMessageFromClient()}>
					From Client
				</button>
			</main>
		</>
	)
}
