import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useManager } from '@/hooks/useManager'

function getServerStatus() {
	const url = `${process.env.SERVER_HTTP_PROTOCOL}://${process.env.SERVER_DOMAIN}/ping`

	fetch(url, {
		method: 'GET',
		mode: 'no-cors',
	})
}

export default function Home() {
	const { players, restartGame } = useManager()

	return (
		<>
			<Head>
				<title>Trivia</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<h1>Hello World!</h1>
				<button onClick={() => restartGame()}>Restart</button>
				<button onClick={() => getServerStatus()}>Fetch Server Status</button>
				<section className={styles.players}>
					{players.map(({ playerId, isConnected }) => (
						<div key={playerId}>{`${
							isConnected ? 'ONLINE' : 'OFFLINE'
						} : ${playerId}`}</div>
					))}
				</section>
			</main>
		</>
	)
}
